export const COUNTRY = [
  {label:'Angola', value:'Angola'},
  {label:'Afghanistan', value:'Afghanistan'},
  {label:'Albania', value:'Albania'},
  {label:'Algeria', value:'Algeria'},
  {label:'Andorra', value:'Andorra'},
  {label:'Anguilla', value:'Anguilla'},
  {label:'Barbuda Antigua', value:'Barbuda Antigua'},
  {label:'Argentina', value:'Argentina'},
  {label:'Armenia', value:'Armenia'},
  {label:'Australia', value:'Australia'},
  {label:'Austria', value:'Austria'},
  {label:'Azerbaijan', value:'Azerbaijan'},
  {label:'Bahamas', value:'Bahamas'},
  {label:'Bahrain', value:'Bahrain'},
  {label:'Bangladesh', value:'Bangladesh'},
  {label:'Barbados', value:'Barbados'},
  {label:'Belarus', value:'Belarus'},
  {label:'Belgium', value:'Belgium'},
  {label:'Belize', value:'Belize'},
  {label:'Benin', value:'Benin'},
  {label:'Bermuda Is.', value:'Bermuda Is.'},
  {label:'Bolivia', value:'Bolivia'},
  {label:'Botswana', value:'Botswana'},
  {label:'Brazil', value:'Brazil'},
  {label:'Brunei', value:'Brunei'},
  {label:'Bulgaria', value:'Bulgaria'},
  {label:'Burkina-faso', value:'Burkina-faso'},
  {label:'Burma', value:'Burma'},
  {label:'Burundi', '  text':'Burundi'},
  {label:'Cameroon', value:'Cameroon'},
  {label:'Canada', value:'Canada'},
  {label:'Central African Republic', value:'Central African Republic'},
  {label:'Chad', value:'Chad'},
  {label:'Chile', value:'Chile'},
  {label:'China', value:'China'},
  {label:'Colombia', value:'Colombia'},
  {label:'Congo', value:'Congo'},
  {label:'Cook Is.', value:'Cook Is.'},
  {label:'Costa Rica', value:'Costa Rica'},
  {label:'Cuba', value:'Cuba'},
  {label:'Cyprus', value:'Cyprus'},
  {label:'Czech Republic', value:'Czech Republic'},
  {label:'Denmark', value:'Denmark'},
  {label:'Djibouti', value:'Djibouti'},
  {label:'Dominica Rep', value:'Dominica Rep'},
  {label:'Ecuador', value:'Ecuador'},
  {label:'Egypt', value:'Egypt'},
  {label:'EI Salvador', value:'EI Salvador'},
  {label:'Estonia', value:'Estonia'},
  {label:'Ethiopia', value:'Ethiopia'},
  {label:'Fiji', value:'Fiji'},
  {label:'Finland', value:'Finland'},
  {label:'France', value:'France'},
  {label:'French Guiana', value:'French Guiana'},
  {label:'Gabon', value:'Gabon'},
  {label:'Gambia', value:'Gambia'},
  {label:'Georgia', value:'Georgia'},
  {label:'Germany', value:'Germany'},
  {label:'Ghana', value:'Ghana'},
  {label:'Gibraltar', value:'Gibraltar'},
  {label:'Greece', value:'Greece'},
  {label:'Grenada', value:'Grenada'},
  {label:'Guam', value:'Guam'},
  {label:'Guatemala', value:'Guatemala'},
  {label:'Guinea', value:'Guinea'},
  {label:'Guyana', value:'Guyana'},
  {label:'Haiti', value:'Haiti'},
  {label:'Honduras', value:'Honduras'},
  {label:'Hongkong', value:'Hongkong'},
  {label:'Hungary', value:'Hungary'},
  {label:'Iceland', value:'Iceland'},
  {label:'India', value:'India'},
  {label:'Indonesia', value:'Indonesia'},
  {label:'Iran', value:'Iran'},
  {label:'Iraq', value:'Iraq'},
  {label:'Ireland', value:'Ireland'},
  {label:'Israel', value:'Israel'},
  {label:'Italy', value:'Italy'},
  {label:'Jamaica', value:'Jamaica'},
  {label:'Japan', value:'Japan'},
  {label:'Jordan', value:'Jordan'},
  {label:'Kampuchea (Cambodia)', value:'Kampuchea (Cambodia)'},
  {label:'Kazakstan', value:'Kazakstan'},
  {label:'Kenya', value:'Kenya'},
  {label:'Korea', value:'Korea'},
  {label:'Kuwait', value:'Kuwait'},
  {label:'Kyrgyzstan', value:'Kyrgyzstan'},
  {label:'Laos', value:'Laos'},
  {label:'Latvia', value:'Latvia'},
  {label:'Lebanon', value:'Lebanon'},
  {label:'Lesotho', value:'Lesotho'},
  {label:'Liberia', value:'Liberia'},
  {label:'Libya', value:'Libya'},
  {label:'Liechtenstein', value:'Liechtenstein'},
  {label:'Lithuania', value:'Lithuania'},
  {label:'Luxembourg', value:'Luxembourg'},
  {label:'Macao', value:'Macao'},
  {label:'Madagascar', value:'Madagascar'},
  {label:'Malawi', value:'Malawi'},
  {label:'Malaysia', value:'Malaysia'},
  {label:'Maldives', value:'Maldives'},
  {label:'Mali', value:'Mali'},
  {label:'Malta', value:'Malta'},
  {label:'Mauritius', value:'Mauritius'},
  {label:'Mexico', value:'Mexico'},
  {label:'Moldova', value:'Moldova'},
  {label:'Monaco', value:'Monaco'},
  {label:'Mongolia', value:'Mongolia'},
  {label:'Montserrat Is.', value:'Montserrat Is.'},
  {label:'Morocco', value:'Morocco'},
  {label:'Mozambique', value:'Mozambique'},
  {label:'Namibia', value:'Namibia'},
  {label:'Nauru', value:'Nauru'},
  {label:'Nepal', value:'Nepal'},
  {label:'Netherlands', value:'Netherlands'},
  {label:'New Zealand', value:'New Zealand'},
  {label:'Nicaragua', value:'Nicaragua'},
  {label:'Niger', value:'Niger'},
  {label:'Nigeria', value:'Nigeria'},
  {label:'North Korea', value:'North Korea'},
  {label:'Norway', value:'Norway'},
  {label:'Oman', value:'Oman'},
  {label:'Pakistan', value:'Pakistan'},
  {label:'Panama', value:'Panama'},
  {label:'Papua New Cuinea', value:'Papua New Cuinea'},
  {label:'Paraguay', value:'Paraguay'},
  {label:'Peru', value:'Peru'},
  {label:'Philippines', value:'Philippines'},
  {label:'Poland', value:'Poland'},
  {label:'French Polynesia', value:'French Polynesia'},
  {label:'Portugal', value:'Portugal'},
  {label:'Puerto Rico', value:'Puerto Rico'},
  {label:'Qatar', value:'Qatar'},
  {label:'Romania', value:'Romania'},
  {label:'Russia', value:'Russia'},
  {label:'Saint Lueia', value:'Saint Lueia'},
  {label:'Saint Vincent', value:'Saint Vincent'},
  {label:'San Marino', value:'San Marino'},
  {label:'Sao Tome and Principe', value:'Sao Tome and Principe'},
  {label:'Saudi Arabia', value:'Saudi Arabia'},
  {label:'Senegal', value:'Senegal'},
  {label:'Seychelles', value:'Seychelles'},
  {label:'Sierra Leone', value:'Sierra Leone'},
  {label:'Singapore', value:'Singapore'},
  {label:'Slovakia', value:'Slovakia'},
  {label:'Slovenia', value:'Slovenia'},
  {label:'Solomon Is.', value:'Solomon Is.'},
  {label:'Somali', value:'Somali'},
  {label:'South Africa', value:'South Africa'},
  {label:'Spain', value:'Spain'},
  {label:'Sri Lanka', value:'Sri Lanka'},
  {label:'Sudan', value:'Sudan'},
  {label:'Suriname', value:'Suriname'},
  {label:'Swaziland', value:'Swaziland'},
  {label:'Sweden', value:'Sweden'},
  {label:'Switzerland', value:'Switzerland'},
  {label:'Syria', value:'Syria'},
  {label:'Taiwan', value:'Taiwan'},
  {label:'Tajikstan', value:'Tajikstan'},
  {label:'Tanzania', value:'Tanzania'},
  {label:'Thailand', value:'Thailand'},
  {label:'Togo', value:'Togo'},
  {label:'Tonga', value:'Tonga'},
  {label:'Trinidad and Tobago', value:'Trinidad and Tobago'},
  {label:'Tunisia', value:'Tunisia'},
  {label:'Turkey', value:'Turkey'},
  {label:'Turkmenistan', value:'Turkmenistan'},
  {label:'Uganda', value:'Uganda'},
  {label:'Ukraine', value:'Ukraine'},
  {label:'United Arab Emirates', value:'United Arab Emirates'},
  {label:'United Kiongdom', value:'United Kiongdom'},
  {label:'United States of America', value:'United States of America'},
  {label:'Uruguay', value:'Uruguay'},
  {label:'Uzbekistan', value:'Uzbekistan'},
  {label:'Venezuela', value:'Venezuela'},
  {label:'Vietnam', value:'Vietnam'},
  {label:'Yemen', value:'Yemen'},
  {label:'Yugoslavia', value:'Yugoslavia'},
  {label:'Zimbabwe', value:'Zimbabwe'},
  {label:'Zaire', value:'Zaire'},
  {label:'Zambia', value:'Zambia'}
]
